pu_user_homepage:
    path:     /
    defaults: { _controller: PuUserBundle:Default:index }
registration:
    path:     /register
    defaults: { _controller: PuUserBundle:Account:register}
user_new:
    path:     /%admin_path%/user/new
    defaults: { _controller: PuUserBundle:Account:new}
user_edit:
    path:     /%admin_path%/user/edit
    defaults: { _controller: PuUserBundle:Account:edit}
user_list:
    path:     /%admin_path%/user/list
    defaults: { _controller: PuUserBundle:Account:list}
login:
    path:     /login
    defaults: { _controller: PuUserBundle:Login:login}
role_new:
    path:     /role/new
    defaults: { _controller: PuUserBundle:Role:new}
role_list:
    path:     /role/list
    defaults: { _controller: PuUserBundle:Role:list}
login_check:
    path:     /security_check
    defaults: {_controller: PuUserBundle:Login:securityCheck }