
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

test_render:
    path:     /render
    defaults: { _controller: ModsetMoPicOneBundle:Mod:form}
tpl:
    path:     /tpl/{id}
    defaults: { _controller: AppBundle:Tpl:render}
    requirements:
        id: '\d+'
test_mod:
    path:     /mod/{mod}/{action}
    defaults: { _controller: AppBundle:Mod:render}
    requirements:
        action: 'render|form'
#User
registration:
    path:     /register
    defaults: { _controller: AppBundle:User/Account:register}
user_new:
    path:     /%admin_path%/user/new
    defaults: { _controller: AppBundle:User/Account:new}
user_edit:
    path:     /%admin_path%/user/edit
    defaults: { _controller: AppBundle:User/Account:edit}
user_list:
    path:     /%admin_path%/user/list
    defaults: { _controller: AppBundle:User/Account:list}
login:
    path:     /login
    defaults: { _controller: AppBundle:User/Login:login}
role_new:
    path:     /%admin_path%/role/new
    defaults: { _controller: AppBundle:User/Role:new}
role_list:
    path:     /%admin_path%/role/list
    defaults: { _controller: AppBundle:User/Role:list}
login_check:
    path:     /security_check
    defaults: {_controller: AppBundle:User/Login:securityCheck }

#Mod
mod_new:
    path:     /%admin_path%/mod/new
    defaults: { _controller: AppBundle:Mod:new }
mod_edit:
    path:     /%admin_path%/mod/edit/{id}
    defaults: { _controller: AppBundle:Mod:edit }
    requirements:
        id: '[0-9A-Za-z]+'
mod_list:
    path:     /%admin_path%/mod/list
    defaults: { _controller: AppBundle:Mod:list }
#tpl
tpl_new:
    path:     /%admin_path%/tpl/new
    defaults: { _controller: AppBundle:Tpl:new }
tpl_edit:
    path:     /%admin_path%/tpl/edit/{id}
    defaults: { _controller: AppBundle:Tpl:edit }
    requirements:
        id: '[0-9A-Za-z]+'
tpl_list:
    path:     /%admin_path%/tpl/list
    defaults: { _controller: AppBundle:Tpl:list }
tpl_show:
    path:     /tpl/{id}
    defaults: { _controller: AppBundle:Tpl:render }
    requirements:
        id: '[0-9A-Za-z]+'
#/
admin_home:
    path:     /admin
    defaults: { _controller: AppBundle:Index:home }
home:
    path:     /
    defaults: { _controller: AppBundle:Home:home}