modset_mo_pic_one:
    resource: "@ModsetMoPicOneBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

test_render:
    path:     /render
    defaults: { _controller: ModsetMoPicOneBundle:Mod:form}

#User
registration:
    path:     /register
    defaults: { _controller: AppBundle:User/Account:register}
user_new:
    path:     /%admin_path%/user/new
    defaults: { _controller: AppBundle:User/Account:new}
user_edit:
    path:     /%admin_path%/user/edit
    defaults: { _controller: AppBundle:User/Account:edit}
user_list:
    path:     /%admin_path%/user/list
    defaults: { _controller: AppBundle:User/Account:list}
login:
    path:     /login
    defaults: { _controller: AppBundle:User/Login:login}
role_new:
    path:     /%admin_path%/role/new
    defaults: { _controller: AppBundle:User/Role:new}
role_list:
    path:     /%admin_path%/role/list
    defaults: { _controller: AppBundle:User/Role:list}
login_check:
    path:     /security_check
    defaults: {_controller: AppBundle:User/Login:securityCheck }

#Mod
mod_new:
    path:     /%admin_path%/mod/new
    defaults: { _controller: AppBundle:Mod/Mod:new }
mod_edit:
    path:     /%admin_path%/mod/edit
    defaults: { _controller: AppBundle:Mod/Mod:edit }
mod_list:
    path:     /%admin_path%/mod/list
    defaults: { _controller: AppBundle:Mod/Mod:list }

#/
admin_home:
    path:     /admin
    defaults: { _controller: AppBundle:Index:home }
home:
    path:     /
    defaults: { _controller: AppBundle:Home:home}